spring:
#  security:
#    user:
#      name: user
#      password: devdojo
  config:
    import: optional:classpath:.env[.properties]
  application:
    name:
      user-service
  threads:
    virtual:
      enabled: true

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER:root}
    password: ${ENV_ROOT_PASSWORD:root123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    academy.devdojo: debug
    net.ttddyy.dsproxy.listener: debug
    org.springframework.security: debug

server:
  port: 8090
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 20
  error:
    include-stacktrace: ON_PARAM
    include-binding-errors: ALWAYS
    include-message: ALWAYS
